clean:
	./gradlew clean

build:
	./gradlew clean build

run-dist:
	./build/install/app/bin/app

test:
	./gradlew test

lint:
	./gradlew checkstyleMain checkstyleTest

report:
	./gradlew jacocoTestReport

.PHONY: build