name: self-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
           gradle-version: 8.5
      - name: Build with Gradle
         #run: ./gradlew build
      - name: Quality check
         run: ./gradlew checkstyleMain
         run: ./gradlew checkstyleTest
         run: ./gradlew test
      - name: Publish code coverage
      	uses: paambaati/codeclimate-action@v5.0.0
        env:
           TEST_REPORTER_ID: ${{secrets.TEST_REPORTER_ID}}
      	   JACOCO_SOURCE_PATH: src/main/java
      	with:
      	   coverageCommand: make report
           coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
