name: self-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
         run: make build
      - name: Quality check
         run: make lint
         run: make test
      - name: Publish code coverage
      	uses: paambaati/codeclimate-action@v5.0.0
        env:
           TEST_REPORTER_ID: ${{secrets.TEST_REPORTER_ID}}
      	   JACOCO_SOURCE_PATH: src/main/java
      	with:
      	   coverageCommand: make report
           coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
